#!/usr/bin/env node

// Script to generate an Emergency Decryption Key (DEK)
function generateEmergencyDEK() {
  // Generate a random 32-byte (256-bit) key
  const keyBytes = new Uint8Array(32);
  for (let i = 0; i < 32; i++) {
    keyBytes[i] = Math.floor(Math.random() * 256);
  }

  // Convert to hex string
  const hexKey = '0x' + Array.from(keyBytes)
    .map(b => b.toString(16).padStart(2, '0'))
    .join('');

  return hexKey;
}

function main() {
  console.log('🔐 Emergency Decryption Key (DEK) Generator');
  console.log('==========================================');

  const dek = generateEmergencyDEK();

  console.log('\n🎯 Generated Emergency DEK:');
  console.log(dek);

  console.log('\n📋 Usage in Smart Contract:');
  console.log(`// In patient registration:`);
  console.log(`const emergencyDEK = "${dek}";`);
  console.log(`await contract.registerPatient(emergencyDEK, surrogateAddress, allowedTypes, allowedRoles);`);

  console.log('\n🔒 Security Notes:');
  console.log('- This key should be encrypted before storage in production');
  console.log('- In real systems, this would be generated by secure key management');
  console.log('- The key enables emergency decryption of patient medical records');
  console.log('- Access is time-limited (4 hours) and heavily audited');

  console.log('\n✨ DEK ready for emergency healthcare access control!');
}

main();