/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace EmergencyAccess {
      
    export type AccessLogStruct = {doctor: AddressLike, patient: AddressLike, emergencyType: string, timestamp: BigNumberish, expiresAt: BigNumberish, justificationSubmitted: boolean, flaggedForEthicsReview: boolean}

    export type AccessLogStructOutput = [doctor: string, patient: string, emergencyType: string, timestamp: bigint, expiresAt: bigint, justificationSubmitted: boolean, flaggedForEthicsReview: boolean] & {doctor: string, patient: string, emergencyType: string, timestamp: bigint, expiresAt: bigint, justificationSubmitted: boolean, flaggedForEthicsReview: boolean }
  
    }

  export interface EmergencyAccessInterface extends Interface {
    getFunction(nameOrSignature: "ACCESS_DURATION" | "JUSTIFICATION_WINDOW" | "accessLogs" | "attestDoctor" | "doctors" | "getAccessLog" | "getLogCount" | "hospitals" | "patients" | "registerHospital" | "registerPatient" | "requestEmergencyAccess" | "submitJustification" | "triggerEthicsReview"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "DoctorAttested" | "EmergencyAccessDenied" | "EmergencyAccessGranted" | "EthicsReviewTriggered" | "HospitalRegistered" | "JustificationSubmitted" | "PatientRegistered"): EventFragment;

    encodeFunctionData(functionFragment: 'ACCESS_DURATION', values?: undefined): string;
encodeFunctionData(functionFragment: 'JUSTIFICATION_WINDOW', values?: undefined): string;
encodeFunctionData(functionFragment: 'accessLogs', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'attestDoctor', values: [AddressLike, string]): string;
encodeFunctionData(functionFragment: 'doctors', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getAccessLog', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getLogCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'hospitals', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'patients', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'registerHospital', values: [string]): string;
encodeFunctionData(functionFragment: 'registerPatient', values: [BytesLike, AddressLike, string[], string[]]): string;
encodeFunctionData(functionFragment: 'requestEmergencyAccess', values: [AddressLike, string]): string;
encodeFunctionData(functionFragment: 'submitJustification', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'triggerEthicsReview', values: [BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'ACCESS_DURATION', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'JUSTIFICATION_WINDOW', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'accessLogs', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'attestDoctor', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'doctors', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getAccessLog', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getLogCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'hospitals', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'patients', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'registerHospital', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'registerPatient', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'requestEmergencyAccess', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'submitJustification', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'triggerEthicsReview', data: BytesLike): Result;
  }

  
    export namespace DoctorAttestedEvent {
      export type InputTuple = [doctor: AddressLike, hospital: AddressLike, role: string];
      export type OutputTuple = [doctor: string, hospital: string, role: string];
      export interface OutputObject {doctor: string, hospital: string, role: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace EmergencyAccessDeniedEvent {
      export type InputTuple = [doctor: AddressLike, patient: AddressLike, reason: string];
      export type OutputTuple = [doctor: string, patient: string, reason: string];
      export interface OutputObject {doctor: string, patient: string, reason: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace EmergencyAccessGrantedEvent {
      export type InputTuple = [doctor: AddressLike, patient: AddressLike, emergencyType: string, expiresAt: BigNumberish];
      export type OutputTuple = [doctor: string, patient: string, emergencyType: string, expiresAt: bigint];
      export interface OutputObject {doctor: string, patient: string, emergencyType: string, expiresAt: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace EthicsReviewTriggeredEvent {
      export type InputTuple = [logIndex: BigNumberish];
      export type OutputTuple = [logIndex: bigint];
      export interface OutputObject {logIndex: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace HospitalRegisteredEvent {
      export type InputTuple = [hospital: AddressLike, name: string];
      export type OutputTuple = [hospital: string, name: string];
      export interface OutputObject {hospital: string, name: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace JustificationSubmittedEvent {
      export type InputTuple = [logIndex: BigNumberish, doctor: AddressLike];
      export type OutputTuple = [logIndex: bigint, doctor: string];
      export interface OutputObject {logIndex: bigint, doctor: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PatientRegisteredEvent {
      export type InputTuple = [patient: AddressLike];
      export type OutputTuple = [patient: string];
      export interface OutputObject {patient: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface EmergencyAccess extends BaseContract {
    
    connect(runner?: ContractRunner | null): EmergencyAccess;
    waitForDeployment(): Promise<this>;

    interface: EmergencyAccessInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    ACCESS_DURATION: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    JUSTIFICATION_WINDOW: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    accessLogs: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, string, string, bigint, bigint, boolean, boolean] & {doctor: string, patient: string, emergencyType: string, timestamp: bigint, expiresAt: bigint, justificationSubmitted: boolean, flaggedForEthicsReview: boolean }],
      'view'
    >
    

    
    attestDoctor: TypedContractMethod<
      [doctor: AddressLike, role: string, ],
      [void],
      'nonpayable'
    >
    

    
    doctors: TypedContractMethod<
      [arg0: AddressLike, ],
      [[boolean, string, string] & {registered: boolean, role: string, attestingHospital: string }],
      'view'
    >
    

    
    getAccessLog: TypedContractMethod<
      [i: BigNumberish, ],
      [EmergencyAccess.AccessLogStructOutput],
      'view'
    >
    

    
    getLogCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    hospitals: TypedContractMethod<
      [arg0: AddressLike, ],
      [[boolean, string] & {verified: boolean, name: string }],
      'view'
    >
    

    
    patients: TypedContractMethod<
      [arg0: AddressLike, ],
      [[boolean, boolean, string, string] & {registered: boolean, emergencyAccessEnabled: boolean, emergencyDEK: string, surrogateContact: string }],
      'view'
    >
    

    
    registerHospital: TypedContractMethod<
      [name: string, ],
      [void],
      'nonpayable'
    >
    

    
    registerPatient: TypedContractMethod<
      [emergencyDEK: BytesLike, surrogate: AddressLike, allowedTypes: string[], allowedRoles: string[], ],
      [void],
      'nonpayable'
    >
    

    
    requestEmergencyAccess: TypedContractMethod<
      [patientAddr: AddressLike, emergencyType: string, ],
      [string],
      'nonpayable'
    >
    

    
    submitJustification: TypedContractMethod<
      [logIndex: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    triggerEthicsReview: TypedContractMethod<
      [logIndex: BigNumberish, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'ACCESS_DURATION'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'JUSTIFICATION_WINDOW'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'accessLogs'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, string, string, bigint, bigint, boolean, boolean] & {doctor: string, patient: string, emergencyType: string, timestamp: bigint, expiresAt: bigint, justificationSubmitted: boolean, flaggedForEthicsReview: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'attestDoctor'): TypedContractMethod<
      [doctor: AddressLike, role: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'doctors'): TypedContractMethod<
      [arg0: AddressLike, ],
      [[boolean, string, string] & {registered: boolean, role: string, attestingHospital: string }],
      'view'
    >;
getFunction(nameOrSignature: 'getAccessLog'): TypedContractMethod<
      [i: BigNumberish, ],
      [EmergencyAccess.AccessLogStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getLogCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'hospitals'): TypedContractMethod<
      [arg0: AddressLike, ],
      [[boolean, string] & {verified: boolean, name: string }],
      'view'
    >;
getFunction(nameOrSignature: 'patients'): TypedContractMethod<
      [arg0: AddressLike, ],
      [[boolean, boolean, string, string] & {registered: boolean, emergencyAccessEnabled: boolean, emergencyDEK: string, surrogateContact: string }],
      'view'
    >;
getFunction(nameOrSignature: 'registerHospital'): TypedContractMethod<
      [name: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'registerPatient'): TypedContractMethod<
      [emergencyDEK: BytesLike, surrogate: AddressLike, allowedTypes: string[], allowedRoles: string[], ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'requestEmergencyAccess'): TypedContractMethod<
      [patientAddr: AddressLike, emergencyType: string, ],
      [string],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'submitJustification'): TypedContractMethod<
      [logIndex: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'triggerEthicsReview'): TypedContractMethod<
      [logIndex: BigNumberish, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'DoctorAttested'): TypedContractEvent<DoctorAttestedEvent.InputTuple, DoctorAttestedEvent.OutputTuple, DoctorAttestedEvent.OutputObject>;
getEvent(key: 'EmergencyAccessDenied'): TypedContractEvent<EmergencyAccessDeniedEvent.InputTuple, EmergencyAccessDeniedEvent.OutputTuple, EmergencyAccessDeniedEvent.OutputObject>;
getEvent(key: 'EmergencyAccessGranted'): TypedContractEvent<EmergencyAccessGrantedEvent.InputTuple, EmergencyAccessGrantedEvent.OutputTuple, EmergencyAccessGrantedEvent.OutputObject>;
getEvent(key: 'EthicsReviewTriggered'): TypedContractEvent<EthicsReviewTriggeredEvent.InputTuple, EthicsReviewTriggeredEvent.OutputTuple, EthicsReviewTriggeredEvent.OutputObject>;
getEvent(key: 'HospitalRegistered'): TypedContractEvent<HospitalRegisteredEvent.InputTuple, HospitalRegisteredEvent.OutputTuple, HospitalRegisteredEvent.OutputObject>;
getEvent(key: 'JustificationSubmitted'): TypedContractEvent<JustificationSubmittedEvent.InputTuple, JustificationSubmittedEvent.OutputTuple, JustificationSubmittedEvent.OutputObject>;
getEvent(key: 'PatientRegistered'): TypedContractEvent<PatientRegisteredEvent.InputTuple, PatientRegisteredEvent.OutputTuple, PatientRegisteredEvent.OutputObject>;

    filters: {
      
      'DoctorAttested(address,address,string)': TypedContractEvent<DoctorAttestedEvent.InputTuple, DoctorAttestedEvent.OutputTuple, DoctorAttestedEvent.OutputObject>;
      DoctorAttested: TypedContractEvent<DoctorAttestedEvent.InputTuple, DoctorAttestedEvent.OutputTuple, DoctorAttestedEvent.OutputObject>;
    

      'EmergencyAccessDenied(address,address,string)': TypedContractEvent<EmergencyAccessDeniedEvent.InputTuple, EmergencyAccessDeniedEvent.OutputTuple, EmergencyAccessDeniedEvent.OutputObject>;
      EmergencyAccessDenied: TypedContractEvent<EmergencyAccessDeniedEvent.InputTuple, EmergencyAccessDeniedEvent.OutputTuple, EmergencyAccessDeniedEvent.OutputObject>;
    

      'EmergencyAccessGranted(address,address,string,uint256)': TypedContractEvent<EmergencyAccessGrantedEvent.InputTuple, EmergencyAccessGrantedEvent.OutputTuple, EmergencyAccessGrantedEvent.OutputObject>;
      EmergencyAccessGranted: TypedContractEvent<EmergencyAccessGrantedEvent.InputTuple, EmergencyAccessGrantedEvent.OutputTuple, EmergencyAccessGrantedEvent.OutputObject>;
    

      'EthicsReviewTriggered(uint256)': TypedContractEvent<EthicsReviewTriggeredEvent.InputTuple, EthicsReviewTriggeredEvent.OutputTuple, EthicsReviewTriggeredEvent.OutputObject>;
      EthicsReviewTriggered: TypedContractEvent<EthicsReviewTriggeredEvent.InputTuple, EthicsReviewTriggeredEvent.OutputTuple, EthicsReviewTriggeredEvent.OutputObject>;
    

      'HospitalRegistered(address,string)': TypedContractEvent<HospitalRegisteredEvent.InputTuple, HospitalRegisteredEvent.OutputTuple, HospitalRegisteredEvent.OutputObject>;
      HospitalRegistered: TypedContractEvent<HospitalRegisteredEvent.InputTuple, HospitalRegisteredEvent.OutputTuple, HospitalRegisteredEvent.OutputObject>;
    

      'JustificationSubmitted(uint256,address)': TypedContractEvent<JustificationSubmittedEvent.InputTuple, JustificationSubmittedEvent.OutputTuple, JustificationSubmittedEvent.OutputObject>;
      JustificationSubmitted: TypedContractEvent<JustificationSubmittedEvent.InputTuple, JustificationSubmittedEvent.OutputTuple, JustificationSubmittedEvent.OutputObject>;
    

      'PatientRegistered(address)': TypedContractEvent<PatientRegisteredEvent.InputTuple, PatientRegisteredEvent.OutputTuple, PatientRegisteredEvent.OutputObject>;
      PatientRegistered: TypedContractEvent<PatientRegisteredEvent.InputTuple, PatientRegisteredEvent.OutputTuple, PatientRegisteredEvent.OutputObject>;
    
    };
  }