/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { EmergencyAccess } from './EmergencyAccess.js';
export * as factories from './factories/index.js';
export { EmergencyAccess__factory } from './factories/EmergencyAccess__factory.js';